### PR TITLE
Use pip for install

### PR DESCRIPTION
**Pull request by antarcticrainforest**
I noticed that the docs do not build anymore and realised that this is due to a discrepancy between the requirements in the `setup.py` and the packages listed in the requirements_ci.yml file. Ideally, we don't want to maintain two locations where dependencies are set. Hence I suggest using the ones defined in the `setup.py` and installing all requirements with pip instead of conda. 

I know this has some potential drawbacks but I think it's still better than maintaining two dependency locations.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@antarcticrainforest Fingers crossed. But that's no guarantee to work in all cases.

**Comment by kmuehlbauer** [comment]
@antarcticrainforest Just want to remind, that the "old" required tests can be removed in the repo-settings under "branch-protection".

**Comment by antarcticrainforest** [comment]
> @antarcticrainforest Fingers crossed. But that's no guarantee to work in all cases.

Absolutely, especially given how troublesome cartopy is. I wish there was a library saving the same purpose that didn't cause some much trouble. Actually, it's quite and amazing thing, the only thing that bugs me is that is constantly causes trouble in the tests with different versions.

**Comment by antarcticrainforest** [comment]
The changes are mainly just cosmetics. Any thoughts?

**Pull request merged**
